# Generated by Django 5.2.9 on 2025-12-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
